spring:
  application:
    name:  deal
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/banking?currentSchema=deal
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
      eclipselink:
        logging:
          level:
            org.hibernate.type.descriptor.sql: trace
  liquibase:
    change-log: db-changelog.xml
    enabled: true
    default-schema: liquibase_data



server:
  port: 8080

#http://localhost:8080/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  obfuscate:
    headers:
      - Authorization
      - X-Secret

calculator:
  base-url: ${CALCULATOR_BASE_URL:http://calculator:8080}
