services:
  postgres:
    image: postgres:15
    container_name: banking-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  calculator:
    build:
      context: ./calculator
    ports:
      - "8080:8080"

  deal:
    build:
      context: ./deal
    ports:
      - "8081:8080"