version: '2.4'

services:
  postgres:
    image: postgres:15
    container_name: banking-postgres
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - global.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATASOURCE_USERNAME}" ]
      interval: 3s
      timeout: 3s
      retries: 3

  calculator:
    build:
      context: calculator
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  deal:
    build:
      context: deal
    ports:
      - "8081:8080"
      - "5005:5005"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - global.env


  statement:
    build:
      context: statement
    ports:
      - "8082:8080"
    depends_on:
      - deal