spring:
  application:
    name:  statement

server:
  port: 8080

#http://localhost:8080/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  obfuscate:
    headers:
      - Authorization
      - X-Secret

deal:
  base-url: ${DEAL_BASE_URL:http://deal:8080}