name: сияй

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build and run tests
        run: mvn clean verify -B -pl ,!integration-tests

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

  codecov:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JaCoCo report
        uses: actions/download-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true

  sonarcloud:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          sonar-token: ${{secrets.SONAR_TOKEN}}
          extra-args: >
            -Dsonar.projectKey=mi-gand_banking-mvp
            -Dsonar.organization=mi-gand
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml